version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
  auth:
    build: .
    command: yarn dev:auth
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    ports:
      - "3001:3000"
      - "9230:9229"
  postgraphile:
    build: .
    command: yarn dev:graphql
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - auth
      - postgres

